--
-- PostgreSQL database dump
--

\restrict 0utgRt4MBaDHBM4fTpc2kBR7tHZQkhpBogN73CAfteiVWuXn0dJdSmHiw6dDHmq

-- Dumped from database version 17.11 (Debian 17.11-1.pgdg13+2)
-- Dumped by pg_dump version 18.6

-- Started on 2026-09-28 01:14:45

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 232 (class 1259 OID 16490)
-- Name: bookings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bookings (
    id integer NOT NULL,
    user_id integer,
    screening_id integer NOT NULL,
    customer_email text NOT NULL,
    status text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT bookings_status_valid CHECK ((status = ANY (ARRAY['confirmed'::text, 'cancelled'::text])))
);


--
-- TOC entry 233 (class 1259 OID 16508)
-- Name: bookings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bookings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16389)
-- Name: cinemas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cinemas (
    id integer NOT NULL,
    name text NOT NULL,
    city text NOT NULL,
    address text NOT NULL
);


--
-- TOC entry 218 (class 1259 OID 16396)
-- Name: cinemas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cinemas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cinemas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16432)
-- Name: genres; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.genres (
    id integer NOT NULL,
    name text NOT NULL
);


--
-- TOC entry 226 (class 1259 OID 16441)
-- Name: genres_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.genres ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.genres_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16397)
-- Name: halls; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.halls (
    id integer NOT NULL,
    cinema_id integer NOT NULL,
    name text NOT NULL
);


--
-- TOC entry 220 (class 1259 OID 16404)
-- Name: halls_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.halls ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.halls_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16442)
-- Name: movie_genres; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.movie_genres (
    movie_id integer NOT NULL,
    genre_id integer NOT NULL
);


--
-- TOC entry 223 (class 1259 OID 16423)
-- Name: movies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.movies (
    id integer NOT NULL,
    title text NOT NULL,
    description text NOT NULL,
    duration_minutes integer NOT NULL,
    release_date date,
    age_rating text NOT NULL,
    poster_url text,
    trailer_url text,
    CONSTRAINT movies_duration_positive CHECK ((duration_minutes > 0))
);


--
-- TOC entry 224 (class 1259 OID 16431)
-- Name: movies_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.movies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16457)
-- Name: screenings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.screenings (
    id integer NOT NULL,
    movie_id integer NOT NULL,
    hall_id integer NOT NULL,
    starts_at timestamp with time zone NOT NULL,
    ends_at timestamp with time zone NOT NULL,
    price numeric(10,2) NOT NULL,
    language text NOT NULL,
    subtitles text,
    format text NOT NULL,
    status text NOT NULL,
    CONSTRAINT screenings_price_positive CHECK ((price > (0)::numeric)),
    CONSTRAINT screenings_status_valid CHECK ((status = ANY (ARRAY['scheduled'::text, 'cancelled'::text]))),
    CONSTRAINT screenings_time_valid CHECK ((ends_at > starts_at))
);


--
-- TOC entry 229 (class 1259 OID 16477)
-- Name: screenings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.screenings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.screenings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16410)
-- Name: seats; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.seats (
    id integer NOT NULL,
    hall_id integer NOT NULL,
    row_number integer NOT NULL,
    seat_number integer NOT NULL
);


--
-- TOC entry 222 (class 1259 OID 16422)
-- Name: seats_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.seats ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.seats_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 16510)
-- Name: tickets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tickets (
    id integer NOT NULL,
    booking_id integer NOT NULL,
    screening_id integer NOT NULL,
    seat_id integer NOT NULL,
    price numeric(10,2) NOT NULL,
    status text NOT NULL,
    hall_id integer NOT NULL,
    CONSTRAINT tickets_price_positive CHECK ((price > (0)::numeric)),
    CONSTRAINT tickets_status_valid CHECK ((status = ANY (ARRAY['valid'::text, 'cancelled'::text])))
);


--
-- TOC entry 235 (class 1259 OID 16534)
-- Name: tickets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tickets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tickets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 16478)
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id integer NOT NULL,
    name text NOT NULL,
    email text NOT NULL,
    password_hash text NOT NULL,
    role text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT user_role_valid CHECK ((role = ANY (ARRAY['admin'::text, 'customer'::text])))
);


--
-- TOC entry 231 (class 1259 OID 16489)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3355 (class 2606 OID 16537)
-- Name: bookings bookings_id_screening_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT bookings_id_screening_unique UNIQUE (id, screening_id);


--
-- TOC entry 3357 (class 2606 OID 16497)
-- Name: bookings bookings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT bookings_pkey PRIMARY KEY (id);


--
-- TOC entry 3329 (class 2606 OID 16395)
-- Name: cinemas cinemas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cinemas
    ADD CONSTRAINT cinemas_pkey PRIMARY KEY (id);


--
-- TOC entry 3341 (class 2606 OID 16440)
-- Name: genres genres_name_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.genres
    ADD CONSTRAINT genres_name_unique UNIQUE (name);


--
-- TOC entry 3343 (class 2606 OID 16438)
-- Name: genres genres_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.genres
    ADD CONSTRAINT genres_pkey PRIMARY KEY (id);


--
-- TOC entry 3331 (class 2606 OID 16403)
-- Name: halls halls_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.halls
    ADD CONSTRAINT halls_pkey PRIMARY KEY (id);


--
-- TOC entry 3345 (class 2606 OID 16446)
-- Name: movie_genres movie_genres_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movie_genres
    ADD CONSTRAINT movie_genres_pkey PRIMARY KEY (movie_id, genre_id);


--
-- TOC entry 3339 (class 2606 OID 16429)
-- Name: movies movies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movies
    ADD CONSTRAINT movies_pkey PRIMARY KEY (id);


--
-- TOC entry 3347 (class 2606 OID 16544)
-- Name: screenings screenings_id_hall_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.screenings
    ADD CONSTRAINT screenings_id_hall_unique UNIQUE (id, hall_id);


--
-- TOC entry 3349 (class 2606 OID 16463)
-- Name: screenings screenings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.screenings
    ADD CONSTRAINT screenings_pkey PRIMARY KEY (id);


--
-- TOC entry 3333 (class 2606 OID 16421)
-- Name: seats seats_hall_row_number_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seats
    ADD CONSTRAINT seats_hall_row_number_unique UNIQUE (hall_id, row_number, seat_number);


--
-- TOC entry 3335 (class 2606 OID 16546)
-- Name: seats seats_id_hall_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seats
    ADD CONSTRAINT seats_id_hall_unique UNIQUE (id, hall_id);


--
-- TOC entry 3337 (class 2606 OID 16414)
-- Name: seats seats_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seats
    ADD CONSTRAINT seats_pkey PRIMARY KEY (id);


--
-- TOC entry 3359 (class 2606 OID 16518)
-- Name: tickets tickets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT tickets_pkey PRIMARY KEY (id);


--
-- TOC entry 3351 (class 2606 OID 16486)
-- Name: users users_email_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_unique UNIQUE (email);


--
-- TOC entry 3353 (class 2606 OID 16484)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 3360 (class 1259 OID 16535)
-- Name: tickets_valid_seat_unique; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX tickets_valid_seat_unique ON public.tickets USING btree (screening_id, seat_id) WITH (deduplicate_items='true') WHERE (status = 'valid'::text);


--
-- TOC entry 3367 (class 2606 OID 16503)
-- Name: bookings bookings_screening_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT bookings_screening_fk FOREIGN KEY (screening_id) REFERENCES public.screenings(id);


--
-- TOC entry 3368 (class 2606 OID 16498)
-- Name: bookings bookings_user_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT bookings_user_fk FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 3361 (class 2606 OID 16405)
-- Name: halls halls_cinema_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.halls
    ADD CONSTRAINT halls_cinema_fk FOREIGN KEY (cinema_id) REFERENCES public.cinemas(id);


--
-- TOC entry 3363 (class 2606 OID 16452)
-- Name: movie_genres movie_genres_genre_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movie_genres
    ADD CONSTRAINT movie_genres_genre_fk FOREIGN KEY (genre_id) REFERENCES public.genres(id);


--
-- TOC entry 3364 (class 2606 OID 16447)
-- Name: movie_genres movie_genres_movie_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.movie_genres
    ADD CONSTRAINT movie_genres_movie_fk FOREIGN KEY (movie_id) REFERENCES public.movies(id);


--
-- TOC entry 3365 (class 2606 OID 16469)
-- Name: screenings screenings_hall_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.screenings
    ADD CONSTRAINT screenings_hall_fk FOREIGN KEY (hall_id) REFERENCES public.halls(id);


--
-- TOC entry 3366 (class 2606 OID 16464)
-- Name: screenings screenings_movie_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.screenings
    ADD CONSTRAINT screenings_movie_fk FOREIGN KEY (movie_id) REFERENCES public.movies(id);


--
-- TOC entry 3362 (class 2606 OID 16415)
-- Name: seats seats_hall_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.seats
    ADD CONSTRAINT seats_hall_fk FOREIGN KEY (hall_id) REFERENCES public.halls(id);


--
-- TOC entry 3369 (class 2606 OID 16519)
-- Name: tickets tickets_booking_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT tickets_booking_fk FOREIGN KEY (booking_id) REFERENCES public.bookings(id);


--
-- TOC entry 3370 (class 2606 OID 16538)
-- Name: tickets tickets_booking_screening_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT tickets_booking_screening_fk FOREIGN KEY (booking_id, screening_id) REFERENCES public.bookings(id, screening_id);


--
-- TOC entry 3371 (class 2606 OID 16524)
-- Name: tickets tickets_screening_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT tickets_screening_fk FOREIGN KEY (screening_id) REFERENCES public.screenings(id);


--
-- TOC entry 3372 (class 2606 OID 16547)
-- Name: tickets tickets_screening_hall_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT tickets_screening_hall_fk FOREIGN KEY (screening_id, hall_id) REFERENCES public.screenings(id, hall_id);


--
-- TOC entry 3373 (class 2606 OID 16529)
-- Name: tickets tickets_seat_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT tickets_seat_fk FOREIGN KEY (seat_id) REFERENCES public.seats(id);


--
-- TOC entry 3374 (class 2606 OID 16552)
-- Name: tickets tickets_seat_hall_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tickets
    ADD CONSTRAINT tickets_seat_hall_fk FOREIGN KEY (seat_id, hall_id) REFERENCES public.seats(id, hall_id);


-- Completed on 2026-09-28 01:14:45

--
-- PostgreSQL database dump complete
--

\unrestrict 0utgRt4MBaDHBM4fTpc2kBR7tHZQkhpBogN73CAfteiVWuXn0dJdSmHiw6dDHmq

